### ISSUE TITLE
Create npm package and publish

### ISSUE THREAD

**Issue by joaovictortr** [lhcgoncalves/bootstrap-modallery#1]
Create Javascript package (with Bootstrap as a dependency) and publish on npm. This would allow one to install it using npm, gulp, bower and alike.

**Comment by operfildoluiz** [comment]
Hi, @joaovictortr!

I'm sorry for the delay.

This plugin will be migrated to NPM and I'm planning to increase many other great functionalities, like Slide effect, lazy loading, Material Design support, mobile-first applying and others.

Your suggestion was accepted and will be released very soon o/

Feel free to collaborate or send more ideas :)
