### ISSUE TITLE
Provide a live demo

### ISSUE THREAD

**Issue by joaovictortr** [lhcgoncalves/bootstrap-modallery#2]
For now, one can only see the source code of the demo. It would be nice to see a live page that shows the functionalities. Perhaps using JSFiddle

**Comment by operfildoluiz** [comment]
I'm waiting for jsDelivr's approval to use the files in jsFiddle.

**Comment by operfildoluiz** [comment]
There is: https://jsfiddle.net/lhcgoncalves/fLtsnqx7/

I'll update Bootsnipp link asap.

Thanks!
