### ISSUE TITLE
Auto-rotate

### ISSUE THREAD

**Issue by petrakid** [lhcgoncalves/bootstrap-modallery#4]
Great gallery!  It's clean and looks great in Bootstrap.

How would one go about adding an auto rotate or auto advance feature where, when the modal loads with the gallery, it will automatically progress to the next image after so many seconds?

**Comment by operfildoluiz** [comment]
Hi, @petrakid!

I'm sorry for the delay. I had some troubles with my email account :/

This plugin will be migrated to NPM and I'm planning to increase many other great functionalities, like Slide effect, lazy loading, Material Design support, mobile-first applying and others.

Your suggestion was accepted and will be released very soon o/

Feel free to collaborate or send more ideas :)
